name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Publish
      run: dotnet publish OrchardCore\src\OrchardCore.Cms.Web\OrchardCore.Cms.Web.csproj -c Release -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: milawski/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
